### ISSUE TITLE
ci.itch.ovh certificate expired

### ISSUE THREAD

**Issue by FredericJacobs** [itchio/wharf#4]
Since it's signed by LetsEncrypt, I guess there is a problem with the Let's Encrypt client on the server.

<img width="481" alt="screen shot 2016-04-12 at 13 20 47" src="https://cloud.githubusercontent.com/assets/400296/14458437/6809be54-00b1-11e6-8b81-06487a5fb65c.png">

**Comment by fasterthanlime** [comment]
@FredericJacobs the ci.itch.ovh domain is retired, we've migrated from Jenkins to GitLab & our instance is at https://git.itch.ovh/.
